/**
 * UI Localization Dictionary
 * Centralized strings allow easy future translation (e.g. Amharic / French / Oromo)
 */

export const STRINGS = {
  app: {
    name: 'CampusCast',
    tagline: 'Tell your class in 10 seconds.',
    subTagline: 'Instant Telegram broadcasts for Ethiopian & global university lecturers',
    botHandle: '@CampusCastTrialBot',
  },
  auth: {
    welcomeBack: 'Welcome back, Lecturer',
    createAccount: 'Create your Lecturer Account',
    loginSubtitle: 'Broadcast updates directly to your students on Telegram.',
    signupSubtitle: 'Set up your classes and connect with your students in seconds.',
    fullName: 'Full Name',
    fullNamePlaceholder: 'e.g. Dr. Abebe Kebede',
    email: 'University or Personal Email',
    emailPlaceholder: 'lecturer@university.edu',
    password: 'Password',
    passwordPlaceholder: '••••••••',
    logIn: 'Log In',
    signUp: 'Create Account',
    continueWithGoogle: 'Continue with Google',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    fillAllFields: 'Please fill in all required fields.',
    invalidEmail: 'Please enter a valid email address.',
    passwordTooShort: 'Password must be at least 6 characters long.',
    demoAccountNotice: 'Demo Mode: Any email and password works instantly.',
    quickDemoLogin: 'Quick Demo as Dr. Abebe Kebede',
  },
  home: {
    myClasses: 'My Classes',
    activeClassesDesc: 'Select a class to send instant announcements or drop files.',
    addClass: 'Add Class',
    searchPlaceholder: 'Search by department, batch/entry, or section...',
    totalSubscribers: 'Active Students',
    totalBroadcasts: 'Sent Broadcasts',
    copyCode: 'Copy',
    copied: 'Copied!',
    active: 'Active',
    inactive: 'Inactive',
    studentsCount: 'students',
    noClassesFound: 'No classes found',
    noClassesMatchSearch: 'No classes match your search query.',
    emptyStateTitle: 'Add your first class',
    emptyStateDesc: 'Generate a Telegram join code for your lecture group and start broadcasting in seconds.',
    createFirstClassBtn: 'Create New Class',
  },
  classForm: {
    newTitle: 'Create New Class',
    editTitle: 'Edit Class Section',
    selectDepartmentLabel: 'Academic Department / Program',
    selectDepartmentPlaceholder: '-- Select Department --',
    customDepartmentLabel: 'Enter Custom Department Name',
    customDepartmentPlaceholder: 'e.g. Biomedical Science, Civil Engineering',
    selectEntryYearLabel: 'Entry Year / Batch',
    selectEntryYearPlaceholder: '-- Select Entry Batch (e.g. 2015 - 2026 Entry) --',
    customEntryYearLabel: 'Custom Entry Year / Cohort',
    customEntryYearPlaceholder: 'e.g. 2014 Entry, 2027 Entry',
    selectSectionLabel: 'Class Section (Section A - H)',
    selectSectionPlaceholder: '-- Select Section (Section A to H) --',
    joinCodeLabel: 'Telegram Join Code',
    joinCodeHelp: 'Unique code students send to @CampusCastBot to join your channel. Auto-generated uppercase.',
    checkingAvailability: 'Checking availability...',
    codeAvailable: 'Join code is available',
    codeTaken: 'Code already taken by another class',
    codeInvalid: 'Code must be at least 3 characters with no spaces',
    activeStatusLabel: 'Active Section',
    activeStatusHelp: 'Inactive sections will pause notifications but preserve history.',
    saveChanges: 'Save Changes',
    createSection: 'Create Section',
    deleteSection: 'Delete Section',
    deleteConfirmTitle: 'Delete this class section?',
    deleteConfirmDesc: 'This will remove the section and its subscriber link permanently. Past broadcasts will be lost.',
    cancel: 'Cancel',
    confirmDelete: 'Yes, Delete Class',
  },
  section: {
    backToClasses: 'All Classes',
    copyJoinCode: 'Copy Code',
    copiedJoinCode: 'Copied!',
    showOnScreen: 'Show on Screen',
    activeSubscribers: 'Active Students',
    editClass: 'Settings',
    tabs: {
      broadcast: 'Broadcast',
      history: 'History',
    },
  },
  projector: {
    title: 'Join Class Telegram Channel',
    instruction1: 'Open Telegram on your phone',
    instruction2: 'Search for @CampusCastBot',
    instruction3: 'Send command:',
    tapToDismiss: 'Tap anywhere or press ESC to close',
    copiedCode: 'Code copied to clipboard!',
    copyLink: 'Copy Telegram Direct Link',
    copiedLink: 'Direct link copied!',
  },
  broadcast: {
    quickActionsTitle: 'Select Announcement Type',
    quickActions: {
      canceled: 'Class Canceled',
      canceledSub: 'Notify of cancelation',
      late: 'Running Late',
      lateSub: 'Share start delay',
      roomChange: 'Room Change',
      roomChangeSub: 'Update lecture hall',
      fileDrop: 'File Drop',
      fileDropSub: 'Share PDF / slides',
      custom: 'Custom Note',
      customSub: 'Freeform update',
    },
    canceledNoteLabel: 'Cancelation Details / Next Steps (Optional)',
    canceledDefaultNote: 'Today\'s lecture is canceled. Please check the online portal for assigned readings and assignment deadlines.',
    lateSelectLabel: 'How many minutes are you running late?',
    lateMin15: '15 min',
    lateMin30: '30 min',
    lateMin45: '45 min',
    lateCustom: 'Custom',
    lateCustomPlaceholder: 'e.g. 20',
    lateNoteLabel: 'Instructions for Students (Optional)',
    lateDefaultNote: 'Please take your seats in the lecture hall. We will begin promptly once I arrive.',
    roomInputLabel: 'New Lecture Room / Venue',
    roomInputPlaceholder: 'e.g. Hall B-204, Main Amphitheater',
    roomNoteLabel: 'Additional Room Details (Optional)',
    roomDefaultNote: 'Please proceed to the new hall now. Class starts at the regular scheduled time.',
    fileUploadTitle: 'Attach Document or Presentation',
    fileUploadSubtitle: 'Supports PDF, PPTX, DOCX, XLSX, Images (Max 20 MB)',
    fileCaptionLabel: 'File Description / Caption',
    fileCaptionPlaceholder: 'e.g. Chapter 4 Lecture Slides & Problem Set',
    generalNoteLabel: 'Add a personal note for students (Optional)',
    generalNotePlaceholder: 'Write any extra instructions, reminders, or office hours info...',
    previewTitle: 'Telegram Live Preview',
    previewSubtitle: 'Exactly what students see on their Telegram app',
    broadcastBtn: 'Broadcast to Students',
    broadcastBtnWithCount: (count: number) => `Broadcast to ${count} Students`,
    confirmTitle: 'Confirm Broadcast',
    confirmBody: (count: number, subject: string, section: string) => 
      `Are you ready to send this announcement to ${count} active students in ${subject} (${section})?`,
    confirmSubtext: 'Students will receive an instant Telegram push notification.',
    cancelBtn: 'Go Back',
    sendNowBtn: 'Send Now',
    sendingMessage: 'Broadcasting to Telegram subscribers...',
    successTitle: 'Broadcast Delivered!',
    successSummary: (delivered: number, failed: number) =>
      `Successfully delivered to ${delivered} student${delivered === 1 ? '' : 's'}${failed > 0 ? `, ${failed} failed` : ''}.`,
    sendAnotherBtn: 'Send Another Announcement',
    viewInHistoryBtn: 'View in History',
  },
  history: {
    title: 'Broadcast History',
    subtitle: 'All announcements sent to this section via Telegram.',
    emptyTitle: 'No broadcasts yet',
    emptyDesc: 'Announcements and files you send will appear here with delivery receipts.',
    sendFirstBtn: 'Send First Broadcast',
    delivered: 'Delivered',
    failed: 'Failed',
    deliveredRate: 'Delivery Rate',
    resend: 'Reuse / Resend',
    openFile: 'Download Attached File',
    filterAll: 'All',
    filterFiles: 'Files Only',
  },
  toast: {
    copied: 'Copied to clipboard!',
    classSaved: 'Class section saved successfully!',
    classDeleted: 'Class section deleted.',
    broadcastSent: 'Broadcast sent to Telegram!',
    errorOccurred: 'An error occurred. Please try again.',
    fileTooLarge: 'File exceeds 20 MB limit.',
    invalidFileType: 'Unsupported file type. Please upload PDF, Word, PPT, Excel, or image files.',
  }
};
